# Generated by Django 4.1.4 on 2022-12-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheat',
            options={'verbose_name': 'шпаргалка', 'verbose_name_plural': 'шпаргалки'},
        ),
    ]
