# Generated by Django 4.1.4 on 2022-12-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheats', '0003_alter_cheat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheats.category', verbose_name='категория'),
        ),
    ]
