# Generated by Django 4.1.4 on 2022-12-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheats', '0004_cheat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheat',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cheats.category', verbose_name='категория'),
        ),
    ]
